# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 377ba30e865a948f241a476a8739dec192138dc75233681825874c8dab96a4ace8a56f59f19f613f5790fa83a7023385ed54cf64a00344adb6b57fee767f8b6e

test:
  secret_key_base: 5808d438715e85ceacf147eee0861a8b8bd0e2cec5bcdfaaecaabd8d3ab1aef2ea7f30e720597bb62241116a7e0431fef171978d84ced7c06daff5ede431e8b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
